-- Codigo exemplo
START TRANSACTION;
USE academia;
COMMIT;
START TRANSACTION;
CREATE TABLE IF NOT EXISTS USUARIOS(
    cpf VARCHAR(11) PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    dt_inicio DATE,
    email VARCHAR(50) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    adm BOOLEAN
);
COMMIT;